Always use the RedisAPI
swisspost/vertx-redisques pull request #184
Opened 2024-06-05 08:48 UTC by dominik-cnx

With this PR we remove below method and always use the RedisAPI

RedisProvider

Future<Redis> connection();

2024-06-05 09:47 UTC, mcweba requested changes

2024-06-05 09:47 UTC, mcweba commented on src/main/java/org/swisspush/redisques/handler/RedisquesHttpRequestHandler.java
> +                        log.error(error, reply.cause());
Make use of new _RedisQuesExceptionFactory_ when logging stacktraces.

2024-06-06 10:30 UTC, hiddenalpha commented
> With this PR we remove below method and always use the RedisAPI

(*Just curious*) How do those two differ?

2024-06-06 10:30 UTC, hiddenalpha approved these changes

2024-06-07 03:26 UTC, dominik-cnx commented
> > With this PR we remove below method and always use the RedisAPI
> 
> (_Just curious_) How do those two differ?

The API holds the connection internally. I'm not entirely sure if we shouldn't use the connection directly, but going through the API seems more like the way to go.


public class RedisAPIImpl implements RedisAPI {

  private static final Logger LOG = LoggerFactory.getLogger(RedisAPIImpl.class);

  private final Redis redis;
  private final RedisConnection connection;

  public RedisAPIImpl(RedisConnection connection) {
    this.connection = connection;
    this.redis = null;
  }

2024-06-07 03:26 UTC, merged

2024-06-07 07:02 UTC, hiddenalpha commented
> The API holds the connection internally. I'm not entirely sure if we shouldn't use the connection directly, but going through the API seems more like the way to go.

Just a thought, could this relate to #165? So maybe we just fixed it?